# Generated by Django 5.1.7 on 2025-03-15 21:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0004_favorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("open_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("day_high", models.DecimalField(decimal_places=2, max_digits=12)),
                ("day_low", models.DecimalField(decimal_places=2, max_digits=12)),
                ("close_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("buy_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("sell_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "benchmark_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["symbol", "timestamp"],
                        name="Authenticat_symbol_a905fc_idx",
                    )
                ],
            },
        ),
    ]
