# Generated by Django 5.1.7 on 2025-03-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Authentication",
            "0006_alter_favorite_unique_together_favorite_exchange_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(max_length=200, verbose_name="Payment ID"),
                ),
                ("order_id", models.CharField(max_length=200, verbose_name="Order ID")),
                (
                    "signature",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Signature"
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="Amount")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
